name: tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: yaml
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Coding style
        run: composer lint
      - name: PHP syntax
        run: find src test -name '*.php' -print0 | xargs -0 -n1 php -l
      - name: Unit tests
        run: composer test
